# Generated by Django 4.2.4 on 2023-08-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("cost", models.DecimalField(decimal_places=3, max_digits=5)),
                (
                    "protein_percent",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                ("fat_percent", models.DecimalField(decimal_places=3, max_digits=5)),
                ("fibre_percent", models.DecimalField(decimal_places=3, max_digits=5)),
                ("salt_percent", models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
