# Generated by Django 4.2.4 on 2023-08-23 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customproductapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
